apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-watcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: load-watcher-extension-apiserver
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: load-watcher
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: load-watcher
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: load-watcher
      hostNetwork: true
      containers:
      - name: load-watcher
        command:
        - /bin/load-watcher
        image: quay.io/husky_parul/load-watcher:latest
        imagePullPolicy: Always
        volumeMounts: 
        - mountPath: /etc/kubernetes/
          name: shared
        env:
        - name: METRICS_PROVIDER_NAME
          value: "Prometheus"
        - name: METRICS_PROVIDER_ADDRESS
          value: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
      volumes:
      - name: shared
        hostPath:
          path: /etc/kubernetes/
          type: Directory

