apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nle
            image: quay.io/husky_parul/nle:latest
            imagePullPolicy: IfNotPresent
            command:
            - python3
            - /app/node-label-envoy.py
          restartPolicy: OnFailure
